### ISSUE TITLE
[Task List]

### ISSUE THREAD

**Issue by DevAndromeda** [CesiumLabs/illustrator.js#1]
- [x] basic layers api
- [x] toolbox
  - [x] image tool
  - [x] background color tool
  - [x] `createAnimation` api for GIF output
  - [x] shapes tool
  - [x] text tool
  - [x] blur tool
  - [x] sharpen tool
- [x] image filters
  - [x] grayscale
  - [x] sepia
  - [x] invert
- [x] Color utilities api
